### ISSUE TITLE
Could u help me fix this

### ISSUE THREAD

**Issue by itzanuragsinghania** [papayalove/movie_recommendation#1]
g.credentials = service_account.Credentials.from_service_account_file('homework0-b1ec1bd9b9fd.json')

**Comment by papayalove** [comment]
Hello,
you need to download a credentials of GCP file yourself. The title below is my GCP project name. So you can use the bigquery in it to store data


Best,
Kaiwen Liu













在 2020-11-20 13:54:06，"Anurag Singhania" <notifications@github.com> 写道：

g.credentials = service_account.Credentials.from_service_account_file('homework0-b1ec1bd9b9fd.json')
